#!/bin/env python 

import os.path

source_files = Split('cpacketringbuffer.cpp\
                 cplayloop.cpp\
                 cresampler.cpp\
		         cfilterdef.cpp\
                 cfixpointresampler.cpp\
                 cmuroad.cpp\
                 main.cpp\
                 cplayer.cpp\
                 crecvloop.cpp\
                 cringbuffer.cpp')


Import('env')

ds_libs = Split('dsaudio sock++')
ext_libs = Split('boost_date_time boost_program_options asound m')

if '-DFIXPOINT' in env['CXXFLAGS']:
  pass
else:
  source_files += ['cfloatresampler.cpp']
  ext_libs += ['samplerate']


target_name = env.Program('muroad', LIBS=ds_libs + ext_libs ,source=source_files)

target_path = os.path.join(env['prefix'], "bin")

print "installing ", target_name, " into ", target_path

install_name = env.Install(target_path, target_name )
env.Alias('install', target_path)

